query_name: gubaphage.k21
query_sigs: /home/ntpierce/2021-gubaphage/gubaphage.siglist.dna.txt
wort_sigs: /group/ctbrowngrp/irber/data/wort-data/wort-sra/sigs
s3_dir: outputs/wort-sra/sigs
threshold: 0.01
ksize: 21
out_dir: "output.gubaphage-magsearch"
